#!/bin/bash

echo "Select 'expand filesystem', then make sure the machine is configured to boot to command line. Also change the hostname, and then generate new ssh keys. Reboot when prompted." &&
read &&
sudo raspi-config
