#!/bin/bash

sudo apt-get -y install dialog &&

sudo apt-get -y remove --purge --auto-remove x11-common alsa-base alsa-utils cifs-utils dbus desktop-file-utils fontconfig fonts-freefont-ttf gconf2-common gnome-themes-standard-data gsfonts gsfonts-x11 java-common libasound2 libxdmcp6 libxfont1 lxde-icon-theme menu-xdg nfs-common omxplayer penguinspuzzle samba-common smbclient v4l-utils whiptail xdg-utils xfonts-utils xkb-data libraspberrypi-bin libraspberrypi-dev libraspberrypi-doc libraspberrypi0 fbset ncdu parted build-essential debconf-utils gdb linux-libc-dev pkg-config debian-reference-en info install-info lua5.1 luajit plymouth python-pifacecommon python-pifacedigitalio python-rpi.gpio python3-numpy python3-pifacecommon python3-pifacedigital-scratch-handler python3-pifacedigitalio python3-rpi.gpio raspberrypi-artwork python-serial python3-serial dpkg-dev make cpp libwibble-dev &&

sudo tasksel remove desktop &&

sudo apt-get update &&
sudo apt-get -y upgrade &&
sudo apt-get -y dist-upgrade &&

sudo rm -rf /etc/X11 &&

sudo apt-get -y install ecryptfs-utils lsof etckeeper knockd ssmtp apticron

# Owncloud dependencies
sudo apt-get -y install mysql-server mysql-client nginx-naxsi php5 php5-fpm php5-gd php5-sqlite php5-mysqlnd php5-psql php-xml-parser php5-intl php5-mcrypt php5-curl php5-json &&

echo "Use 'aptitude' to check for any other packages that should be removed; once loaded, type 'l', then '~i!~M' to see all installed non-automatic packages." &&
echo "Reboot at this point to make sure nothing is broken, and also check ps -elf to see what's running"
