#!/bin/bash

printf "Enter new username: " &&
read USERNAME

if id -u "${USERNAME}" &>/dev/null; then
    echo "User already exists"
    exit 1
fi

sudo adduser "${USERNAME}" &&
sudo adduser "${USERNAME}" sudo &&
sudo chmod go-rwx "/home/${USERNAME}" &&
sudo ecryptfs-migrate-home -u "${USERNAME}" &&

echo "Now logout and ssh in as the new user"
