#!/bin/bash

THISUSER="$(id -un)"
if [ "${THISUSER}" = 'pi' ]; then
    echo "Run this as the new user!"
    exit 1
fi

function remove-if-exists()
{
    if id -u "${1}" &>/dev/null; then
        sudo deluser --remove-all-files "${1}"
    fi
}

remove-if-exists pi &&
remove-if-exists games &&
remove-if-exists lp &&
remove-if-exists mail &&
remove-if-exists news &&
remove-if-exists uucp &&
remove-if-exists irc &&
remove-if-exists gnats &&
remove-if-exists messagebus &&
remove-if-exists statd &&
remove-if-exists usbmux &&
remove-if-exists list &&

sudo rm -rf /home/pi &&

function lockout()
{
    sudo passwd -l "${1}" &&
    sudo chsh -s /usr/sbin/nologin "${1}"
}

sudo passwd -l root &&
lockout daemon &&
lockout bin &&
lockout sys &&
lockout sync &&
lockout man &&
lockout proxy &&
lockout www-data &&
lockout backup &&
lockout nobody &&
lockout libuuid &&
lockout sshd &&
lockout ntp &&

echo "Remove all references to user 'pi' from /etc/sudoers"
