#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Port knocker
KNOCKD="${DIR}/knockd"
KNOCKD_TARGET='/etc/default/knockd'
KNOCKD_CONF="${DIR}/knockd.conf"
KNOCKD_CONF_TARGET='/etc/knockd.conf'

SSH_PORT="$(grep '^Port' /etc/ssh/sshd.conf | awk '{print $2}')" &&

printf "Enter port-knocking sequence for ssh; this should be a list of comma-separated ports (optionally postfixed with :tcp or :udp (TCP is the default)), with NO SPACES!: " &&
read SEQUENCE &&

printf "Enter interface for port knocker; usually eth0: " &&
read IFACE &&

TMPFILE="$(mktemp)" &&
sed "s/@@@@@1@@@@@/${SEQUENCE}/g" < "${KNOCKD_CONF}" > "${TMPFILE}" &&
TMPFILE2="$(mktemp)" &&
sed "s/@@@@@2@@@@@/${SSH_PORT}/g" < "${TMPFILE}" > "${TMPFILE2}" &&

sudo cp "${TMPFILE2}" "${KNOCKD_CONF_TARGET}" &&
sudo chown root:root "${KNOCKD_CONF_TARGET}" &&
sudo chmod a=r "${KNOCKD_CONF_TARGET}" &&
sudo chmod go-rwx "${KNOCKD_CONF_TARGET}" &&
rm "${TMPFILE}" &&
rm "${TMPFILE2}" &&

TMPFILE="$(mktemp)" &&
sed "s/@@@@@1@@@@@/${IFACE}/g" < "${KNOCKD}" > "${TMPFILE}" &&
sudo cp "${TMPFILE}" "${KNOCKD_TARGET}" &&
sudo chown root:root "${KNOCKD_TARGET}" &&
sudo chmod a=r "${KNOCKD_TARGET}" &&
sudo chmod go-rwx "${KNOCKD_TARGET}" &&
rm "${TMPFILE}" &&

# IPtables
RULES="${DIR}/iptables.rules" &&
RULES_TARGET='/etc/iptables.rules' &&
SCRIPT="${DIR}/iptables" &&
SCRIPT_TARGET='/etc/network/if-pre-up.d/iptables' &&

sudo cp "${RULES}" "${RULES_TARGET}" &&
sudo chown root:root "${RULES_TARGET}" &&
sudo chmod u=r "${RULES_TARGET}" &&
sudo chmod go-rwx "${RULES_TARGET}" &&

sudo cp "${SCRIPT}" "${SCRIPT_TARGET}" &&
sudo chown root:root "${SCRIPT_TARGET}" &&
sudo chmod u=rx "${SCRIPT_TARGET}" &&
sudo chmod go-rwx "${SCRIPT_TARGET}"
