#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -e '/etc/ssh/authorized_keys' ]; then
    echo "No SSH keys are authorised for login in /etc/ssh/authorized_keys; not going any further!"
    exit 1
fi

SSH_CONFIG='/etc/ssh/sshd_config'

printf "Enter port for SSH (usually 22): " &&
read SSH_PORT &&

# Generate new host keys
sudo rm -f /etc/ssh/ssh_host_* &&
sudo dpkg-reconfigure openssh-server &&

# Setup user's config
mkdir -p "${HOME}/.ssh" &&
chmod go-rwx "${HOME}/.ssh" &&

if [ ! -e "${HOME}/.ssh/id_rsa" ]; then
    ssh-keygen -t rsa
fi

# Setup server config
TMPFILE="$(mktemp)" &&
TMPFILE2="$(mktemp)" &&
sed "s/@@@@@1@@@@@/$(id -un)/g" < "${DIR}/sshd-config-template" > "${TMPFILE}" &&
sed "s/@@@@@2@@@@@/${SSH_PORT}/g" < "${TMPFILE}" > "${TMPFILE2}" &&
sudo cp "${TMPFILE2}" "${SSH_CONFIG}" &&
sudo chown root:root "${SSH_CONFIG}" &&
sudo chmod a=r "${SSH_CONFIG}" &&
rm "${TMPFILE}" &&
rm "${TMPFILE2}" &&
sudo chown root:root /etc/ssh/authorized_keys &&
sudo chmod go-wx /etc/ssh/authorized_keys &&

# Email on login
EMAIL_ON_LOGIN='/etc/ssh/ssh-email-on-login' &&
sudo cp "${DIR}/ssh-email-on-login" "${EMAIL_ON_LOGIN}" &&
sudo chown root:root "${EMAIL_ON_LOGIN}" &&
sudo chmod a=rx "${EMAIL_ON_LOGIN}" &&

PAM_STRING="session optional pam_exec.so seteuid ${EMAIL_ON_LOGIN}" &&
if ! grep "${PAM_STRING}" /etc/pam.d/sshd; then
    echo "${PAM_STRING}" | sudo tee -a /etc/pam.d/sshd >/dev/null
fi

echo "Reboot now and make sure you can still log in! (You'll need to delete known_hosts on the client because the host keys have changed.)"
