#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

APTICRON_CONF="${DIR}/apticron-conf-template"
APTICRON_CONF_TARGET='/etc/apticron/apticron.conf'
EMAIL_DEFAULTS_FILE='/etc/ssmtp/notification-defaults'

FROM="$(grep -i '^From' "${EMAIL_DEFAULTS_FILE}" | awk '{print $2}')" &&
TO="$(grep -i '^To' "${EMAIL_DEFAULTS_FILE}" | awk '{print $2}')" &&

TMPFILE="$(mktemp)" &&
cp "${APTICRON_CONF}" "${TMPFILE}" &&
sed -i "s/@@@@@1@@@@@/${TO}/g" "${TMPFILE}" &&
sed -i "s/@@@@@2@@@@@/$(hostname)/g" "${TMPFILE}" &&
sed -i "s/@@@@@3@@@@@/${FROM}/g" "${TMPFILE}" &&
sudo cp "${TMPFILE}" "${APTICRON_CONF_TARGET}" &&
sudo chown root:root "${APTICRON_CONF_TARGET}" &&
sudo chmod a=r "${APTICRON_CONF_TARGET}" &&
rm "${TMPFILE}"
