#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

CONF="${DIR}/nginx.conf"
CONF_TARGET='/etc/nginx/nginx.conf'

sudo cp "${CONF}" "${CONF_TARGET}" &&
sudo chown root:root "${CONF_TARGET}" &&
sudo chmod a=r "${CONF_TARGET}" &&

sudo rm -f '/etc/nginx/sites-enabled/default'
