#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

CONF="${DIR}/nginx.conf"
CONF_TARGET='/etc/nginx/nginx.conf'

sudo cp "${CONF}" "${CONF_TARGET}" &&
sudo chown root:root "${CONF_TARGET}" &&
sudo chmod a=r "${CONF_TARGET}" &&

sudo rm -f '/etc/nginx/sites-enabled/default' &&

PHP_INI='/etc/php5/fpm/php.ini' &&

if ! grep '^cgi.fix_pathinfo' "${PHP_INI}" &>/dev/null; then
    echo 'cgi.fix_pathinfo=0' | sudo tee -a "${PHP_INI}" >/dev/null
elif grep '^cgi.fix_pathinfo=1$' "${PHP_INI}" >&/dev/null; then
    sudo sed -i 's/^cgi.fix_pathinfo=1$/cgi.fix_pathinfo=0/g' "${PHP_INI}"
elif ! grep '^cgi.fix_pathinfo=0$' "${PHP_INI}"; then
    echo
    echo "Something's up with ${PHP_INI}; better fix it manually"
fi
