#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

printf "Enter the database password to give the newly-created owncloud user: " &&
read -s DATABASE_USER_PW &&

printf "Enter the database root password (created when installing mysql): " &&
read -s DATABASE_ROOT_PW &&

# PHP configuration
CONF_SRC="${DIR}/php-mysql.ini"
CONF_DST='/etc/php5/conf.d/mysql.ini'

sudo cp "${CONF_SRC}" "${CONF_DST}" &&
sudo chown root:root "${CONF_DST}" &&
sudo chmod a=r "${CONF_DST}" &&


# Database configuration
mysql --user=root "--password=${DATABASE_ROOT_PW}" <<EOF &&
CREATE DATABASE IF NOT EXISTS owncloud;
GRANT ALL PRIVILEGES ON owncloud.* TO 'ownclouduser'@'localhost' IDENTIFIED BY '${DATABASE_USER_PW}';
EOF

echo "When configuring owncloud, log into the mysql database using the username 'ownclouduser' and the password you specified here."
