#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

printf "Enter the HTTPS port for OwnCloud (usually 443, but must match the one set in the firewall script): " &&
read HTTPS_PORT &&

printf "Enter the fully-qualified domain name (or IP address, for testing) on which this server will be accessed: " &&
read SERVER_NAME &&


# Install owncloud
APT_SRC="${DIR}/owncloud.list" &&
APT_DIR='/etc/apt/sources.list.d' &&
APT_DST="${APT_DIR}/owncloud.list" &&

sudo mkdir -p "${APT_DIR}" &&
sudo chmod go-w "${APT_DIR}" &&
sudo cp "${APT_SRC}" "${APT_DST}" &&
sudo chown root:root "${APT_DST}" &&
sudo chmod a=r "${APT_DST}" &&

TMPFILE="$(mktemp)" &&
wget http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/Release.key -O "${TMPFILE}" &&
sudo apt-key add - < "${TMPFILE}" &&
rm "${TMPFILE}" &&

sudo apt-get update &&
sudo apt-get install owncloud &&


# Configure nginx

CONF="${DIR}/owncloud-nginx-template" &&
CONF_TARGET='/etc/nginx/sites-enabled/owncloud' &&

TMPFILE="$(mktemp)" &&
cp "${CONF}" "${TMPFILE}" &&
sed -i "s/@@@@@1@@@@@/${HTTPS_PORT}/g" "${TMPFILE}" &&
sed -i "s/@@@@@2@@@@@/${SERVER_NAME}/g" "${TMPFILE}" &&
sudo cp "${TMPFILE}" "${CONF_TARGET}" &&
sudo chown root:root "${CONF_TARGET}" &&
sudo chmod a=r "${CONF_TARGET}" &&
rm "${TMPFILE}" &&


echo &&
echo "Please place the server's certificate at /etc/nginx/${SERVER_NAME}.crt, and the private key at /etc/nginx/${SERVER_NAME}.key"
