#!/bin/bash

PARTITION="$(findmnt -n -o SOURCE /mnt/owncloud-primary)"

if [ ! -z "${PARTITION}" ]; then
    # Spin down after 5 minutes inactivity
    hdparm -S60 "${PARTITION}" > /etc/foobar
else
    echo no drive > /etc/foobar
fi
