#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


echo "Select the correct time zone when prompted: 'Europe/London'" &&
enter-to-continue &&
sudo dpkg-reconfigure tzdata &&

echo "Select the correct locale when prompted: en_GB.UTF-8, and nothing else" &&
enter-to-continue &&
sudo dpkg-reconfigure locales &&

echo "Select the correct keyboard layout when prompted: Generic 105-key (Intl) PC, then English (UK)" &&
enter-to-continue &&
sudo dpkg-reconfigure keyboard-configuration &&


if real-pi; then
    cat <<EOF
About to run raspi-config:
    - select 'expand filesystem'
    - make sure the machine is configured to boot to command line
    - change the hostname
    - give the GPU 16 MB of memory
Reboot when prompted
EOF
    enter-to-continue &&
    sudo raspi-config
fi
