#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


echo "Select the correct time zone when prompted; usually 'Europe/London'" &&
enter-to-continue &&
sudo dpkg-reconfigure tzdata &&

echo "Select the correct locale when prompted; usually en_GB.UTF-8" &&
enter-to-continue &&
sudo dpkg-reconfigure locales &&


if real-pi; then
    cat <<EOF
About to run raspi-config:
    - select 'expand filesystem'
    - make sure the machine is configured to boot to command line
    - change the hostname
    - give the GPU 16 MB of memory
Reboot when prompted
EOF
    enter-to-continue &&
    sudo raspi-config
fi
