#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


SSMTP_CONF='/etc/ssmtp/ssmtp.conf'
sed-install "${DIR}/ssmtp-conf-template" "${SSMTP_CONF}" "${PI_SERVER_EMAIL_TARGET}" "${PI_SERVER_EMAIL_SMTP}" "${PI_SERVER_FQDN}" &&
sudo chmod a=r "${SSMTP_CONF}"


NOTIFICATION_EMAIL="${DIR}/notification-email"
NOTIFICATION_EMAIL_TARGET='/notification-email'
sed-install "${DIR}/send-notification-email" "${PI_SERVER_NOTIFICATION_EMAIL_SCRIPT}" "${PI_SERVER_FROM}" "${PI_SERVER_EMAIL_TARGET}" &&
sudo chmod a=rx "${PI_SERVER_NOTIFICATION_EMAIL_SCRIPT}"
