#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -e '/etc/ssh/authorized_keys' ]; then
    echo "No SSH keys are authorised for login in /etc/ssh/authorized_keys; not going any further!"
    exit 1
fi

SSH_CONFIG='/etc/ssh/sshd_config'
SSH_PORT='22' &&

# Generate new host keys
sudo rm -f /etc/ssh/ssh_host_* &&
sudo dpkg-reconfigure openssh-server &&

# Setup user's config
mkdir -p "${HOME}/.ssh" &&
chmod go-rwx "${HOME}/.ssh" &&

if [ ! -e "${HOME}/.ssh/id_rsa" ]; then
    ssh-keygen -t rsa
fi

# Setup server config
TMPFILE="$(mktemp)" &&
cp "${DIR}/sshd-config-template" "${TMPFILE}" &&
sed -i "s/@@@@@1@@@@@/$(id -un)/g" "${TMPFILE}" &&
sudo cp "${TMPFILE}" "${SSH_CONFIG}" &&
sudo chown root:root "${SSH_CONFIG}" &&
sudo chmod a=r "${SSH_CONFIG}" &&
rm "${TMPFILE}" &&
sudo chown root:root /etc/ssh/authorized_keys &&
sudo chmod go-wx /etc/ssh/authorized_keys &&

# Email on login
EMAIL_ON_LOGIN='/etc/ssh/ssh-email-on-login' &&
sudo cp "${DIR}/ssh-email-on-login" "${EMAIL_ON_LOGIN}" &&
sudo chown root:root "${EMAIL_ON_LOGIN}" &&
sudo chmod a=rx "${EMAIL_ON_LOGIN}" &&

PAM_STRING="session optional pam_exec.so seteuid ${EMAIL_ON_LOGIN}" &&
if ! grep "${PAM_STRING}" /etc/pam.d/sshd; then
    echo "${PAM_STRING}" | sudo tee -a /etc/pam.d/sshd >/dev/null
fi

# Avahi daemon for local name resolution
AVAHI_SRC="${DIR}/avahi-daemon.conf" &&
AVAHI_DST='/etc/avahi/avahi-daemon.conf' &&
sudo cp "${AVAHI_SRC}" "${AVAHI_DST}" &&
sudo chown root:root "${AVAHI_DST}" &&
sudo chmod a=r "${AVAHI_DST}" &&

echo "Reboot now and make sure you can still log in! (You'll need to delete known_hosts on the client because the host keys have changed.)"
