#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# IPtables
RULES="${DIR}/iptables.rules" &&
RULES_TARGET='/etc/iptables.rules' &&
SCRIPT="${DIR}/iptables" &&
SCRIPT_TARGET='/etc/network/if-pre-up.d/iptables' &&

sudo cp "${RULES}" "${RULES_TARGET}" &&
sudo chown root:root "${RULES_TARGET}" &&
sudo chmod u=r "${RULES_TARGET}" &&
sudo chmod go-rwx "${RULES_TARGET}" &&

sudo cp "${SCRIPT}" "${SCRIPT_TARGET}" &&
sudo chown root:root "${SCRIPT_TARGET}" &&
sudo chmod u=rx "${SCRIPT_TARGET}" &&
sudo chmod go-rwx "${SCRIPT_TARGET}" &&


# Enable routing
SYSCTL_CONF='/etc/sysctl.conf'

if ! grep '^net.ipv4.ip_forward' "${SYSCTL_CONF}" &>/dev/null; then
    echo 'net.ipv4.ip_forward=1' | sudo tee -a "${SYSCTL_CONF}" >/dev/null
elif grep '^net.ipv4.ip_forward=0$' "${SYSCTL_CONF}" >&/dev/null; then
    sudo sed -i 's/^net.ipv4.ip_forward=0$/net.ipv4.ip_forward=1/g' "${SYSCTL_CONF}"
elif ! grep '^net.ipv4.ip_forward=1$' "${SYSCTL_CONF}" &>/dev/null; then
    echo
    echo "Something's up with ${SYSCTL_CONF}; better fix it manually"
fi


echo "Reboot to enable the firewall."
