#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

NGINX_CERT='/etc/pi-certs/nginx.crt'
NGINX_KEY='/etc/pi-certs/nginx.key'
CA_CERT='/etc/pi-certs/ca.crt'

function cert-check()
{
    echo "Certificates not present; not going any further"
    echo "Put the certificates at:"
    echo "    Server certificate: ${NGINX_CERT}"
    echo "    Server private key: ${NGINX_KEY}"
    echo "    CA certificate: ${CA_CERT}"
    exit 1
}

test ! -e "${NGINX_CERT}" && cert-check
test ! -e "${NGINX_KEY}" && cert-check
test ! -e "${CA_CERT}" && cert-check

sudo chown root:root "${NGINX_CERT}" "${NGINX_KEY}" "${CA_CERT}" &&
sudo chmod u=r "${NGINX_CERT}" "${NGINX_KEY}" "${CA_CERT}" &&
sudo chmod go-rwx "${NGINX_KEY}" &&
sudo chmod go-wx "${NGINX_CERT}" "${CA_CERT}" &&


SERVER_NAME="$(hostname).local" &&

printf "Enter the relative path under /mnt/owncloud-primary where data should be stored: " &&
read OWNCLOUD_PATH &&

OWNCLOUD_FULL_PATH="/mnt/owncloud-primary/${OWNCLOUD_PATH}" &&
sudo mkdir -p "${OWNCLOUD_FULL_PATH}" &&
sudo chown www-data:www-data "${OWNCLOUD_FULL_PATH}" &&
sudo chmod o-rwx "${OWNCLOUD_FULL_PATH}" &&


# Install owncloud
APT_SRC="${DIR}/owncloud.list" &&
APT_DIR='/etc/apt/sources.list.d' &&
APT_DST="${APT_DIR}/owncloud.list" &&

sudo mkdir -p "${APT_DIR}" &&
sudo chmod go-w "${APT_DIR}" &&
sudo cp "${APT_SRC}" "${APT_DST}" &&
sudo chown root:root "${APT_DST}" &&
sudo chmod a=r "${APT_DST}" &&

TMPFILE="$(mktemp)" &&
wget http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/Release.key -O "${TMPFILE}" &&
sudo apt-key add - < "${TMPFILE}" &&
rm "${TMPFILE}" &&

sudo apt-get update &&
sudo apt-get -y install owncloud &&


# Configure nginx

CONF="${DIR}/owncloud-nginx-template" &&
CONF_TARGET='/etc/nginx/sites-enabled/owncloud' &&

TMPFILE="$(mktemp)" &&
cp "${CONF}" "${TMPFILE}" &&
sed -i "s/@@@@@1@@@@@/${SERVER_NAME}/g" "${TMPFILE}" &&
sudo cp "${TMPFILE}" "${CONF_TARGET}" &&
sudo chown root:root "${CONF_TARGET}" &&
sudo chmod a=r "${CONF_TARGET}" &&
rm "${TMPFILE}" &&

sudo service php5-fpm restart &&
sudo service nginx restart &&

TMPFILE="$(mktemp)" &&
cat >"${TMPFILE}" <<EOF

To configure owncloud, go to https://${SERVER_NAME}, create an admin user, and setup the database as MySQL using the credentials created earlier. The database user is 'ownclouduser', the database name is 'owncloud', and the password is whatever you chose. The data directory should be ${OWNCLOUD_FULL_PATH}.

Once you can login and see the files on the server, go to the menu, select 'admin', and set the following settings:

[Remote Shares]
Untick 'Allow other instances to mount public links shared from this server' -- there won't be any public links...

[Cron]
Tick 'cron'

[Sharing]
Untick 'Allow users to share via link'
Untick 'Allow resharing'

[Security]
Tick 'Enforce HTTPS'

[Email Server]
From address: owncloud@<whatever hostname you entered in script 04-email>


Go to the menu, select 'personal', and fill in the email address field with the address notifications should be sent to.


Go to apps, enable the 'external storage' app, then go back to admin and configure it (TODO...)
EOF

less "${TMPFILE}" &&
rm "${TMPFILE}"
