#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

OPENVPN_CERT='/etc/pi-certs/openvpn.crt'
OPENVPN_KEY='/etc/pi-certs/openvpn.key'
DH='/etc/pi-certs/dh2048.pem'
CA_CERT='/etc/pi-certs/ca.crt'

function cert-check()
{
    echo "Certificates not present; not going any further"
    echo "Put the certificates at:"
    echo "    Server certificate: ${OPENVPN_CERT}"
    echo "    Server private key: ${OPENVPN_KEY}"
    echo "    Diffie-Helman parameters: ${DH}"
    echo "    CA certificate: ${CA_CERT}"
    exit 1
}

test ! -e "${OPENVPN_CERT}" && cert-check
test ! -e "${OPENVPN_KEY}" && cert-check
test ! -e "${DH}" && cert-check
test ! -e "${CA_CERT}" && cert-check

sudo chown root:root "${OPENVPN_CERT}" "${OPENVPN_KEY}" "${DH}" "${CA_CERT}" &&
sudo chmod u=r "${OPENVPN_CERT}" "${OPENVPN_KEY}" "${DH}" "${CA_CERT}" &&
sudo chmod go-rwx "${OPENVPN_KEY}" &&
sudo chmod go-wx "${OPENVPN_CERT}" "${CA_CERT}" "${DH}" &&


CONFIG_SRC="${DIR}/openvpn-server.conf" &&
CONFIG_DST='/etc/openvpn/openvpn-server.conf' &&

sudo cp "${CONFIG_SRC}" "${CONFIG_DST}" &&
sudo chown root:root "${CONFIG_DST}" &&
sudo chmod u=r "${CONFIG_DST}" &&
sudo chmod go-rwx "${CONFIG_DST}"
