#!/bin/bash
# Test whether a TCP port will be opened at boot

PORTFILE='@@@@@1@@@@@'

if [ ! -z "${1}" ]; then
    if [ -f "${PORTFILE}" ]; then
        if grep -x "${1}" "${PORTFILE}" >/dev/null; then
            echo 'Yes'
            exit 0
        fi
    fi
fi

echo 'No'
exit 1
