#!/bin/bash
# Test whether a UDP port will be opened at boot

PORTFILE='/etc/iptables.udp_open_boot'

if [ ! -z "${1}" ]; then
    if [ -f "${PORTFILE}" ]; then
        if grep -x "${1}" "${PORTFILE}" >/dev/null; then
            echo 'Yes'
            exit 0
        fi
    fi
fi

echo 'No'
exit 1
