#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


# Make sure the certificates are in place, and have the correct permissions
CERT_NAME='nginx'
check-pi-server-cert "Nginx" "${CERT_NAME}" &&
sudo chgrp www-data "$(pi-server-key "${CERT_NAME}")" &&
sudo chmod g=r "$(pi-server-key "${CERT_NAME}")" &&


# # Install syncthing
curl -s 'https://syncthing.net/release-key.txt' | sudo apt-key add - &&
echo 'deb http://apt.syncthing.net/ syncthing release' | sudo tee /etc/apt/sources.list.d/syncthing-release.list >/dev/null &&
sudo apt-get update &&
sudo apt-get -y install syncthing &&


# Prepare directories
sudo mkdir -p "${PI_SERVER_SYNCTHING_CONFIG}" &&
sudo chown 'www-data:www-data' "${PI_SERVER_SYNCTHING_CONFIG}" &&
sudo chmod o-rwx "${PI_SERVER_SYNCTHING_CONFIG}"

function cert-link() {
    if ! sudo test -e "${2}"; then
        sudo ln -s "${1}" "${2}"
    fi
}

cert-link "$(pi-server-cert "${CERT_NAME}")" "${PI_SERVER_SYNCTHING_CONFIG}/https-cert.pem" &&
cert-link "$(pi-server-key "${CERT_NAME}")" "${PI_SERVER_SYNCTHING_CONFIG}/https-key.pem" &&


# Make it run at boot
SUPERVISOR_DST='/etc/supervisor/conf.d/syncthing.conf' &&
sed-install "${DIR}/supervisor-syncthing" "${SUPERVISOR_DST}" \
            "${PI_SERVER_SYNCTHING_BINARY}" \
            "${PI_SERVER_SYNCTHING_CONFIG}" \
            'www-data' \
            "${PI_SERVER_DATA_MAIN_DIR}" &&
sudo chmod a=r "${SUPERVISOR_DST}" || exit 1


# Generate initial setup if necessary
if ! sudo test -e "${PI_SERVER_SYNCTHING_CONFIG}/config.xml"; then
    sudo -u 'www-data' "${PI_SERVER_SYNCTHING_BINARY}" "-generate=${PI_SERVER_SYNCTHING_CONFIG}" || exit 1
fi


# Webpage
DST="${PI_SERVER_WEB_PAGE_PARTS_DIR}/00-syncthing" &&
sed-install "${DIR}/webpage-template" "${DST}" &&
sudo chmod a=r "${DST}" &&

sudo "${PI_SERVER_WEB_PAGE_GENERATE}" &&


# Firewall
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open-at-boot 22000 tcp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open-at-boot 21025 udp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open-at-boot 8080 tcp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open 22000 tcp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open 21025 udp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open 8080 tcp &&


# Cleanup
sudo service supervisor restart &&
echo 'About to display instructions' &&
enter-to-continue &&


less <<EOF
Syncthing should now be running on http://${PI_SERVER_IP}:8080.

Configure settings as follows:

GUI Listen Address:
0.0.0.0:8080

Untick 'Enable UPnP'
Untick 'Global Discovery'
Untick 'Automatic Upgrades'
Untick 'Start Browser'

Tick 'Use HTTPS for GUI', and fill in a username and password as desired.


Delete the default folder.


Restart syncthing.


You can then add folders as desired.
EOF
