#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


sudo apt-get update &&
sudo apt-get -y install ntfs-3g supervisor &&


sudo touch "${PI_SERVER_CRON_PAUSE_DIR}/supervisor.service"
