#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" &&
    source "${DIR}/common.bash" &&
    set-pi-server-param "${PI_SERVER_LAN_NETWORK_FILE}" "Enter the network address of the LAN the server is on (usually the server's LAN IP address with the last octet changed to a 0; assumed by the scripts to be a /24 - but don't type the '/24'!)" &&
    set-pi-server-param "${PI_SERVER_VPN_NETWORK_FILE}" "Enter the network address of the VPN subnet to be managed by this server (assumed to be a /24 - type in the network address, with the last octet as 0, and don't type the '/24')" &&
    set-pi-server-param "${PI_SERVER_STORAGE_DRIVE_DEV_FILE}" "Enter the path of the external hard drive device (usually /dev/sda)" &&
    set-pi-server-param "${PI_SERVER_STORAGE_DATA_PARTITION_FILE}" "Enter the partition number of the main data partition on the external hard drive (usually 1)" &&
    set-pi-server-param "${PI_SERVER_STORAGE_BACKUP_PARTITION_FILE}" "Enter the partition number of the backup partition on the external hard drive (usually 2)" &&
    set-pi-server-param "${PI_SERVER_STORAGE_SPINNING_DRIVE_FILE}" "Is the external hard drive a spinning disk? [y/n]"
