#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" &&
    source "${DIR}/common.bash" &&
    set-pi-server-param "${PI_SERVER_LAN_NETWORK_FILE}" "Enter the network address of the LAN the server is on (usually the server's LAN IP address with the last octet changed to a 0; assumed by the scripts to be a /24 - but don't type the '/24'!)" &&
    set-pi-server-param "${PI_SERVER_VPN_NETWORK_FILE}" "Enter the network address of the VPN subnet to be managed by this server (assumed to be a /24 - type in the network address, with the last octet as 0, and don't type the '/24')" &&
