#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


sudo mkdir -p "${PI_SERVER_ZONEEDIT_DIR}" &&


# ZoneEdit boot and cron setup
sed-install "${DIR}/zoneedit-update" "${PI_SERVER_ZONEEDIT_UPDATE_SCRIPT}" \
            "${PI_SERVER_FQDN_FILE}" \
            "${PI_SERVER_ZONEEDIT_USERNAME_FILE}" \
            "${PI_SERVER_ZONEEDIT_PASSWORD_FILE}" \
            "${PI_SERVER_ZONEEDIT_LOG_FILE}" &&
sudo chmod a=rx "${PI_SERVER_ZONEEDIT_UPDATE_SCRIPT}" &&

SCRIPT="${PI_SERVER_NET_UP_SCRIPTS}/zoneedit-at-net-up" &&
sed-install "${DIR}/zoneedit-at-net-up" "${SCRIPT}" \
            "${PI_SERVER_ZONEEDIT_UPDATE_SCRIPT}" \
            "${PI_SERVER_LAN_IFACE_FILE}" &&
sudo chmod a=rx "${SCRIPT}" &&

if [ ! -e '/etc/cron.hourly/zoneedit-update' ]; then
    sudo ln -s "${PI_SERVER_ZONEEDIT_UPDATE_SCRIPT}" '/etc/cron.hourly/zoneedit-update'
fi


# ZoneEdit configuration script
sed-install "${DIR}/zoneedit-config" "${PI_SERVER_ZONEEDIT_CONFIG_SCRIPT}" \
            "${PI_SERVER_ZONEEDIT_USERNAME_FILE}" \
            "${PI_SERVER_ZONEEDIT_PASSWORD_FILE}" &&
sudo chmod a=rx "${PI_SERVER_ZONEEDIT_CONFIG_SCRIPT}" &&


# Config files
function do-config-file() {
    local NAME="${1}"
    local TARGET="${2}"

    if [ ! -e "${TARGET}" ]; then
        echo "# The first non-comment line in this file is used as the ${NAME} for boot-time and cron zoneedit. Leave that line blank to disable." | sudo tee "${TARGET}" &>/dev/null
        sudo chown root:root "${TARGET}"
        sudo chmod u=rw "${TARGET}"
        sudo chmod go-rwx "${TARGET}"
    fi
}

do-config-file 'username' "${PI_SERVER_ZONEEDIT_USERNAME_FILE}" &&
do-config-file 'password' "${PI_SERVER_ZONEEDIT_PASSWORD_FILE}" &&


# Configuration
echo "About to configure ZoneEdit" &&
enter-to-continue &&
"${PI_SERVER_ZONEEDIT_CONFIG_SCRIPT}" &&

echo &&
echo "ZoneEdit settings can be changed with '${PI_SERVER_ZONEEDIT_CONFIG_SCRIPT}'" &&
enter-to-continue
