#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


sudo mkdir -p "${PI_SERVER_CERT_DIR}" &&
sudo chown root:root "${PI_SERVER_CERT_DIR}" &&
sudo chmod u=rwx "${PI_SERVER_CERT_DIR}" &&
sudo chmod go-w "${PI_SERVER_CERT_DIR}" &&


# Make sure the certs are in place, and have the correct permissions
if ! getent group "${PI_SERVER_HTTPS_KEY_GROUP}" &>/dev/null; then
    sudo addgroup "${PI_SERVER_HTTPS_KEY_GROUP}" || exit 1
fi

CERT_NAME='nginx' &&
check-pi-server-cert "Nginx" "${CERT_NAME}" &&

# nginx.key has to be readable by the group, so syncthing can use
# it. This is only used for internally-accessible pages.
sudo chgrp "${PI_SERVER_HTTPS_KEY_GROUP}" "$(pi-server-key "${CERT_NAME}")" &&
sudo chmod g=r "$(pi-server-key "${CERT_NAME}")" &&


# Install the main pi-server site
CONF_TARGET='/etc/nginx/sites-enabled/pi-server' &&
sed-install "${DIR}/pi-server-nginx-template" "${CONF_TARGET}" \
            "${PI_SERVER_WEB_PAGE_DIR}" &&
sudo chmod a=r "${CONF_TARGET}" &&

sudo mkdir -p "${PI_SERVER_WEB_PAGE_DIR}" &&
sed-install "${DIR}/favicon.png" "${PI_SERVER_WEB_PAGE_DIR}/favicon.png" &&
sed-install "${DIR}/favicon-apple.png" "${PI_SERVER_WEB_PAGE_DIR}/favicon-apple.png" &&
sed-install "${DIR}/favicon.ico" "${PI_SERVER_WEB_PAGE_DIR}/favicon.ico" &&
sed-install "${DIR}/pi.css" "${PI_SERVER_WEB_PAGE_DIR}/pi.css" &&
sudo chmod a=r "${PI_SERVER_WEB_PAGE_DIR}/favicon.png" \
     "${PI_SERVER_WEB_PAGE_DIR}/favicon-apple.png" \
     "${PI_SERVER_WEB_PAGE_DIR}/favicon.ico" \
     "${PI_SERVER_WEB_PAGE_DIR}/pi.css" &&

CERT="${PI_SERVER_WEB_PAGE_DIR}/ca.crt" &&
sed-install "${PI_SERVER_CA_CERT}" "${CERT}" &&
sudo chmod a=r "${CERT}" &&

sudo mkdir -p "${PI_SERVER_WEB_PAGE_PARTS_DIR}" &&
sudo touch "${PI_SERVER_WEB_PAGE_PARTS_DIR}/placeholder" &&

sed-install "${DIR}/web-page-header" "${PI_SERVER_WEB_PAGE_HEADER}" \
            "$(hostname)" &&
sudo chmod a=r "${PI_SERVER_WEB_PAGE_HEADER}" &&

sed-install "${DIR}/web-page-footer" "${PI_SERVER_WEB_PAGE_FOOTER}" &&
sudo chmod a=r "${PI_SERVER_WEB_PAGE_FOOTER}" &&

sed-install "${DIR}/main-page-header" "${PI_SERVER_WEB_PAGE_MAIN_HEADER}" \
            "${PI_SERVER_IP}" \
            "$(hostname)" \
            "${PI_SERVER_FQDN}" &&
sudo chmod a=r "${PI_SERVER_WEB_PAGE_MAIN_HEADER}" &&

sed-install "${DIR}/main-page-footer" "${PI_SERVER_WEB_PAGE_MAIN_FOOTER}" \
            "${PI_SERVER_SHUTDOWND_PORT}" &&
sudo chmod a=r "${PI_SERVER_WEB_PAGE_MAIN_FOOTER}" &&

sed-install "${DIR}/generate-main-web-page" "${PI_SERVER_WEB_PAGE_GENERATE}" \
            "${PI_SERVER_WEB_PAGE_DIR}" \
            "${PI_SERVER_WEB_PAGE_PARTS_DIR}" \
            "${PI_SERVER_WEB_PAGE_HEADER}" \
            "${PI_SERVER_WEB_PAGE_FOOTER}" \
            "${PI_SERVER_WEB_PAGE_MAIN_HEADER}" \
            "${PI_SERVER_WEB_PAGE_MAIN_FOOTER}" &&
sudo chmod a=rx "${PI_SERVER_WEB_PAGE_GENERATE}" &&

BOOTSTRAP="${PI_SERVER_WEB_PAGE_DIR}/bootstrap-3.3.7-dist" &&
if [ ! -e "${BOOTSTRAP}" ]; then
    TMPDIR="$(mktemp -d)" &&
    cd "${TMPDIR}" &&
    wget https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip &&
    unzip bootstrap-3.3.7-dist.zip &&
    sudo mv bootstrap-3.3.7-dist "${BOOTSTRAP}" &&
    sudo chown -R www-data:www-data "${BOOTSTRAP}" &&
    cd &&
    rm -r "${TMPDIR}" || exit 1
fi

JQUERY="${PI_SERVER_WEB_PAGE_DIR}/jquery-3.2.1.min.js"
if [ ! -e "${JQUERY}" ]; then
    TMPDIR="$(mktemp -d)" &&
    cd "${TMPDIR}" &&
    wget http://code.jquery.com/jquery-3.2.1.min.js &&
    sudo mv jquery-3.2.1.min.js "${JQUERY}" &&
    sudo chown www-data:www-data "${JQUERY}" &&
    cd &&
    rm -r "${TMPDIR}" || exit 1
fi

sudo "${PI_SERVER_WEB_PAGE_GENERATE}" &&


sudo systemctl restart nginx.service
