#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&

#################
sudo mkdir -p "${PI_SERVER_BACKUP_MAIN_DIR}" "${PI_SERVER_BACKUP_GIT_DIR}" "${PI_SERVER_BACKUP_EMAIL_DIR}" &&
sudo chmod go-rwx "${PI_SERVER_BACKUP_MAIN_DIR}" &&

sudo chown www-data:www-data "${PI_SERVER_BACKUP_GIT_DIR}" &&
sudo chmod go-rwx "${PI_SERVER_BACKUP_GIT_DIR}" &&

# TODO correct permissions on email backup dir
#################


sudo apt-get update &&
sudo apt-get -y install rsnapshot || exit 1


function exists() {
    if [ ! -e "${1}" ]; then
        echo "Deployment key '${1}' does not exist; not going any further!"
        exit 1
    else
        sudo chown www-data:www-data "${1}" &&
        sudo chmod u=r "${1}" &&
        sudo chmod go-rwx "${1}" || return 1
    fi
}

exists "${PI_SERVER_DEPLOYMENT_KEY}" &&
exists "${PI_SERVER_DEPLOYMENT_KEY_PUB}" &&


# Configuration
sudo mkdir -p "${PI_SERVER_BACKUP_CONFIG_DIR}" &&
sudo chown www-data:www-data "${PI_SERVER_BACKUP_CONFIG_DIR}" &&
sudo chmod go-rwx "${PI_SERVER_BACKUP_CONFIG_DIR}" &&

INSTRUCTIONS="${PI_SERVER_BACKUP_CONFIG_DIR}/instructions.txt" &&
sed-install "${DIR}/backup-instructions.txt" "${INSTRUCTIONS}" &&
sudo chown www-data:www-data "${INSTRUCTIONS}" &&
sudo chmod u=r "${INSTRUCTIONS}" &&
sudo chmod go-rwx "${INSTRUCTIONS}" &&

sudo touch "${PI_SERVER_BACKUP_GIT_CONFIG}" &&
sudo chown www-data:www-data "${PI_SERVER_BACKUP_GIT_CONFIG}" &&
sudo chmod go-rwx "${PI_SERVER_BACKUP_GIT_CONFIG}" &&


# Scripts
sudo mkdir -p "${PI_SERVER_BACKUP_SCRIPT_DIR}" &&

RSNAPSHOT_CONF='/etc/rsnapshot.conf'
sed-install "${DIR}/rsnapshot.conf" "${RSNAPSHOT_CONF}" \
            "${PI_SERVER_BACKUP_MAIN_DIR}" \
            "${PI_SERVER_DATA_MAIN_DIR}" \
            "$(hostname)" \
            "${PI_SERVER_DATA_CONFIG_DIR}" &&
sudo chmod a=r "${RSNAPSHOT_CONF}" &&

sed-install "${DIR}/backup-git-ssh" "${PI_SERVER_BACKUP_GIT_SSH}" \
            "${PI_SERVER_DEPLOYMENT_KEY}" &&
sudo chmod a=rx "${PI_SERVER_BACKUP_GIT_SSH}" &&

BACKUP_SCRIPT="${PI_SERVER_CRON_SAFE_DIR}/backup" &&
sed-install "${DIR}/backup.bash" "${BACKUP_SCRIPT}" \
            "${PI_SERVER_BACKUP_LAST_RUN}" \
            "${PI_SERVER_DATA_MAIN_DIR}" \
            "${PI_SERVER_BACKUP_MOUNT_DIR}" \
            "${PI_SERVER_BACKUP_GIT_CONFIG}" \
            "${PI_SERVER_BACKUP_GIT_DIR}" \
            "${PI_SERVER_BACKUP_GIT_SSH}" &&
sudo chmod a=r "${BACKUP_SCRIPT}" &&


cat <<EOF &&

The backup configuration directory is at ${PI_SERVER_BACKUP_CONFIG_DIR} (which you should access using Syncthing).

EOF
enter-to-continue
