#!/bin/bash
# Update a ZoneEdit record

HOST_FILE='@@@@@1@@@@@'
USERNAME_FILE='@@@@@2@@@@@'
PASSWORD_FILE='@@@@@3@@@@@'

test ! -f "${HOST_FILE}" && exit 0
test ! -f "${USERNAME_FILE}" && exit 0
test ! -f "${PASSWORD_FILE}" && exit 0

HOST="$(grep -v '^#' "${HOST_FILE}" | head -n 1)"
USERNAME="$(grep -v '^#' "${USERNAME_FILE}" | head -n 1)"
PASSWORD="$(grep -v '^#' "${PASSWORD_FILE}" | head -n 1)"

test -z "${HOST}" && exit 0
test -z "${USERNAME}" && exit 0
test -z "${PASSWORD}" && exit 0

OUTPUT_FILE='@@@@@4@@@@@'

if ! curl --fail --user "${USERNAME}:${PASSWORD}" "https://dynamic.zoneedit.com/auth/dynamic.html?host=${HOST}" &>"${OUTPUT_FILE}"; then
    echo 'ZoneEdit update failed; check the log file'
fi

chmod u=rw "${OUTPUT_FILE}"
chmod go-rwx "${OUTPUT_FILE}"
