#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


if ! on-pi; then
    # Nothing to do here, since a proper user was set up during installation.
    exit 0
fi


if [ "$(id -un)" = 'pi' ]; then
    read -r -p "Enter new username: " USERNAME &&

        if id -u "${USERNAME}" &>/dev/null; then
            echo "User already exists"
            exit 1
        fi

    sudo adduser "${USERNAME}" &&
    sudo adduser "${USERNAME}" sudo &&
    sudo adduser "${USERNAME}" plugdev &&
    sudo chmod go-rwx "/home/${USERNAME}" &&


    echo &&
    echo "Now log in as the new user (${USERNAME}), clone this repo again, and continue with 03-cleanup-users." &&
    enter-to-continue
fi
