#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


set-pi-server-param "${PI_SERVER_IP_FILE}" "Enter the server's LAN IP address (MUST be correct, or nothing will work!)" &&

set-pi-server-param "${PI_SERVER_LAN_IFACE_FILE}" "Enter the server's LAN interface name (usually the ethernet interface, but may no longer be called eth0)" &&

set-pi-server-param "${PI_SERVER_FQDN_FILE}" "Enter the fully-qualified domain name of the server, as visible externally (the address to be managed by ZoneEdit, and also used as the 'From' in any email sent by the server)"
