#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" || exit 1

# If we're on the testbed, we don't want to mess with vagrant's setup
if [ -e /fakepi-default-route ]; then
    exit 0
fi


# DigitalOcean droplets come pre-configured with a static IP, so we don't
# do anything related to DHCP there
if ! grep digitalocean /etc/apt/sources.list >/dev/null; then

    sudo apt-get update &&
    sudo apt-get -y install dhcpcd5 || exit 1


    INTERFACES='/etc/network/interfaces'
    DHCPCD_CONF='/etc/dhcpcd.conf'

    if on-pi || [ ! -e /fakepi-default-route ]; then
        # We're on a real machine
        sed-install "${DIR}/interfaces-normal" "${INTERFACES}" \
                    "${PI_SERVER_LAN_IFACE}" &&
        sed-install "${DIR}/dhcpcd-conf-template" "${DHCPCD_CONF}" \
                    "${PI_SERVER_LAN_IFACE}" || exit 1
    else
        # We're on a testing VM set up using zz-vm-testing
        sed-install "${DIR}/interfaces-normal" "${INTERFACES}" \
                    "${PI_SERVER_LAN_IFACE}" &&

        cat <<EOF | sudo tee -a "${DHCPCD_CONF}" &>/dev/null
interface ${PI_SERVER_LAN_IFACE}
static domain_name_servers=8.8.8.8
static routers=$(cat '/fakepi-default-route')
EOF
    fi

    sudo chmod a=r "${INTERFACES}" &&
    sudo chmod a=r "${DHCPCD_CONF}" || exit 1
fi
