#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


INTERFACES='/etc/network/interfaces'
DHCPCD_CONF='/etc/dhcpcd.conf'

if on-pi || [ ! -e /fakepi-default-route ]; then
    # We're on a real machine
    if [ -z "${PI_SERVER_WAN_IFACE}" ]; then
        sed-install "${DIR}/interfaces-normal" "${INTERFACES}" \
                    "${PI_SERVER_LAN_IFACE}" &&
        sed-install "${DIR}/dhcpcd-conf-template" "${DHCPCD_CONF}" \
                    "${PI_SERVER_LAN_IFACE}" || exit 1
    else
        sed-install "${DIR}/interfaces-router" "${INTERFACES}" \
                    "${PI_SERVER_WAN_IFACE}" \
                    "${PI_SERVER_LAN_IFACE}" \
                    "${PI_SERVER_IP}" &&
        sed-install "${DIR}/dhcpcd-conf-template" "${DHCPCD_CONF}" \
                    "${PI_SERVER_WAN_IFACE}" || exit 1
    fi
else
    # We're on a testing VM set up using zz-vm-testing
cat <<EOF | sudo tee -a "${DHCPCD_CONF}" &>/dev/null
interface ${PI_SERVER_LAN_IFACE}
static domain_name_servers=8.8.8.8
static routers=$(cat '/fakepi-default-route')
EOF
fi

sudo chmod a=r "${INTERFACES}" &&
sudo chmod a=r "${DHCPCD_CONF}"
