#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


SSHD_CONFIG='/etc/ssh/sshd_config'
SSH_DIR="${HOME}/.ssh"
PRIVATE_KEY="${SSH_DIR}/id_rsa"
PUBLIC_KEY="${SSH_DIR}/id_rsa.pub"
KEYS="${SSH_DIR}/authorized_keys"


# Sanity check
if [ ! -e "${KEYS}" ]; then
    echo "No SSH keys are authorised for login in ${KEYS}; not going any further!"
    exit 1
fi


if on-pi && [ ! -f "${PI_SERVER_SSH_REGENERATED_KEYS}" ]; then
    # Generate new host keys; only needed on Raspbian, which has existing keys pre-installed
    sudo rm -f /etc/ssh/ssh_host_* &&
    sudo dpkg-reconfigure openssh-server &&
    sudo touch "${PI_SERVER_SSH_REGENERATED_KEYS}" || exit 1
fi


# Setup user's config
mkdir -p "${SSH_DIR}" &&
chmod go-rwx "${SSH_DIR}" &&

if [ ! -e "${PRIVATE_KEY}" ]; then
    ssh-keygen -t rsa -f "${PRIVATE_KEY}" || exit 1
fi

chmod u=r "${PRIVATE_KEY}" &&
chmod go-rwx "${PRIVATE_KEY}" &&
chmod a=r "${PUBLIC_KEY}" &&
chmod a=r "${KEYS}" &&
chmod u+w "${KEYS}" &&


# Setup server config
sed-install "${DIR}/sshd-config-template" "${SSHD_CONFIG}" \
            "$(id -un)" &&
sudo chmod a=r "${SSHD_CONFIG}" &&


# Email on login
sed-install "${DIR}/ssh-email-on-login" "${PI_SERVER_SSH_LOGIN_EMAIL_SCRIPT}" \
            "${PI_SERVER_NOTIFICATION_EMAIL_SCRIPT}" &&
sudo chmod a=rx "${PI_SERVER_SSH_LOGIN_EMAIL_SCRIPT}" &&

PAM_STRING="session optional pam_exec.so seteuid ${PI_SERVER_SSH_LOGIN_EMAIL_SCRIPT}" &&
if ! grep "${PAM_STRING}" /etc/pam.d/sshd &>/dev/null; then
    echo "${PAM_STRING}" | sudo tee -a /etc/pam.d/sshd >/dev/null || exit 1
fi


echo "Reboot now and make sure you can still log in! (You may be prompted to remove an entry from known_hosts on the client because the host keys have changed.)" &&
enter-to-continue
