#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


sed-install "${DIR}/check-disk-usage" "${PI_SERVER_DISK_USAGE_SCRIPT}" \
            "${PI_SERVER_NOTIFICATION_EMAIL_SCRIPT}" &&
sudo chmod a=rx "${PI_SERVER_DISK_USAGE_SCRIPT}" &&

TARGET="${PI_SERVER_CRON_NORMAL_DIR}/disk-usage-root"
sed-install "${DIR}/disk-usage-root" "${TARGET}" \
            "${PI_SERVER_DISK_USAGE_SCRIPT}" &&
sudo chmod a=rx "${TARGET}"
