#!/bin/bash
# Send an email if a partitions is above 90% usage

THRESHOLD='90'

if [ -e "${1}" ]; then
    USAGE="$(df "${1}" | grep -o '[0-9]\+%' | grep -o '[0-9]\+')"
    if [ "${USAGE}" -gt "${THRESHOLD}" ]; then
        '@@@@@1@@@@@' 'Storage space alert' "$(printf "A partition is above %s%% full.\n\n%s\n" "${THRESHOLD}" "$(df -h)")"
    fi
fi
