#!/bin/bash
# Send an email when the network connects; intended to monitor reboots

LAN_IFACE="$(cat '@@@@@2@@@@@')"

if [ ! -z "${LAN_IFACE}" ] && [ "${IFACE}" = "${LAN_IFACE}" ]; then
    ( sleep 1m; '@@@@@1@@@@@' "Connected to network" "$(uptime)" ) &
fi

exit 0
