#!/bin/bash
# Run all the pi-server cron scripts

if [ -e '@@@@@1@@@@@' ]; then
    # Cron script disabled
    exit 0
fi

# Run scripts that need services to be paused
if [ -x '@@@@@2@@@@@' ]; then
    '@@@@@2@@@@@'
fi

# Run all other cron scripts
find '@@@@@3@@@@@' -type f -executable | LC_ALL=C sort | while read -r line; do
    "${line}"
done
