#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


sudo apt-get update &&
sudo apt-get -y install minidlna wget curl xsltproc &&


MINIDLNA_DEFAULT='/etc/default/minidlna' &&
sudo sed -i 's/^#USER="minidlna"$/USER="www-data"/g' "${MINIDLNA_DEFAULT}" &&
sudo sed -i 's/^#GROUP="minidlna"$/GROUP="www-data"/g' "${MINIDLNA_DEFAULT}" &&


MINIDLNA_CONF='/etc/minidlna.conf' &&
sed-install "${DIR}/minidlna-conf-template" "${MINIDLNA_CONF}" \
            "${PI_SERVER_MINIDLNA_MEDIA}" \
            "${PI_SERVER_MINIDLNA_DB}" &&
sudo chmod a=r "${MINIDLNA_CONF}" || exit 1



function minidlna-dir()
{
    while (($#)); do
        sudo mkdir -p "${1}"
        sudo chown www-data:www-data "${1}"
        sudo chmod o-rwx "${1}"
        shift
    done
}

minidlna-dir "${PI_SERVER_MINIDLNA_MEDIA}" \
             "${PI_SERVER_MINIDLNA_PODCASTS}" \
             "${PI_SERVER_MINIDLNA_PODCASTS_LISTENED}" \
             "${PI_SERVER_MASHPODDER_CONFIG_REPO}" \
             "${PI_SERVER_MINIDLNA_CONFIG}" \
             "${PI_SERVER_MINIDLNA_DB}" \
             "${PI_SERVER_MASHPODDER_ROOT}" \
             "${PI_SERVER_MASHPODDER_TMP_DIR}" &&

sudo touch "${PI_SERVER_MASHPODDER_RSS_FILE}" &&
sudo chown www-data:www-data "${PI_SERVER_MASHPODDER_RSS_FILE}" &&


# Setup webpage
DST="${PI_SERVER_WEB_PAGE_PARTS_DIR}/01-minidlna" &&
sed-install "${DIR}/webpage-template" "${DST}" \
            "${PI_SERVER_IP}" &&
sudo chmod a=r "${DST}" &&

sudo "${PI_SERVER_WEB_PAGE_GENERATE}" &&


# Firewall
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open-at-boot 8200 tcp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open-at-boot 1900 udp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open 8200 tcp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open 1900 udp &&


CRONJOB='/etc/cron.daily/minidlna-refresh' &&
sed-install "${DIR}/minidlna-cron" "${CRONJOB}" &&
sudo chmod a=rx "${CRONJOB}" &&


# Setup mashpodder
TMPDIR="$(mktemp -d)" &&
REPO="${TMPDIR}/mashpodder" &&
MASHPODDER="${REPO}/mashpodder.sh"
git clone https://github.com/chessgriffin/mashpodder.git "${REPO}" &&
cd "${REPO}" &&
git checkout 0.4.9 &&

sed -i "s|^#BASEDIR=\"\\\$HOME/mashpodder\"\$|BASEDIR='${PI_SERVER_MASHPODDER_SCRIPT_DIR}'|g" "${MASHPODDER}" &&
sed -i "s|^PODCASTDIR=\"\\\$BASEDIR/podcasts\"\$|PODCASTDIR='${PI_SERVER_MINIDLNA_PODCASTS}'|g" "${MASHPODDER}" &&
sed -i "s|^TMPDIR=\"\\\$BASEDIR/tmp\"\$|TMPDIR='${PI_SERVER_MASHPODDER_TMP_DIR}'|g" "${MASHPODDER}" &&
sed -i "s|^RSSFILE=\"\\\$BASEDIR/mp.conf\"\$|RSSFILE='${PI_SERVER_MASHPODDER_RSS_FILE}'|g" "${MASHPODDER}" &&
sed -i "s|^PODLOG=\"\\\$BASEDIR/podcast.log\"\$|PODLOG='${PI_SERVER_MASHPODDER_ROOT}/podcast.log'|g" "${MASHPODDER}" &&

sudo mkdir -p "${PI_SERVER_MASHPODDER_SCRIPT_DIR}" &&

XSLT="${PI_SERVER_MASHPODDER_SCRIPT_DIR}/parse_enclosure.xsl" &&
sed-install "${MASHPODDER}" "${PI_SERVER_MASHPODDER_SCRIPT}" &&
sudo chmod a=rx "${PI_SERVER_MASHPODDER_SCRIPT}" &&
sed-install "${REPO}/parse_enclosure.xsl" "${XSLT}" &&
sudo chmod a=r "${XSLT}" &&

PODCASTS_HELP="${PI_SERVER_MASHPODDER_CONFIG_REPO}/instructions.txt" &&
sudo cp "${DIR}/podcast-instructions.txt" "${PODCASTS_HELP}" &&
sudo chown www-data:www-data "${PODCASTS_HELP}" &&
sudo chmod a=r "${PODCASTS_HELP}" &&

CRONJOB='/etc/cron.daily/mashpodder' &&
sed-install "${DIR}/mashpodder-cron" "${CRONJOB}" \
            "${PI_SERVER_MASHPODDER_RSS_FILE}" \
            "${PI_SERVER_MASHPODDER_SCRIPT}" \
            "${PI_SERVER_MASHPODDER_ROOT}/daily-download.log" \
            "${PI_SERVER_NOTIFICATION_EMAIL_SCRIPT}" &&
sudo chmod a=rx "${CRONJOB}" &&

cd &&
rm -rf "${TMPDIR}" &&


sudo service minidlna force-reload &&


cat <<EOF &&

To add media to the server, place or symlink it in '${PI_SERVER_MINIDLNA_MEDIA}'.

To setup podcasts, see '${PODCASTS_HELP}'.

EOF
enter-to-continue
