# Common stuff; should be sourced, not run!

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../01-core/common.bash"

export PI_SERVER_MEDIA_SCRIPT_DIR="${PI_SERVER_DIR}/media-server"
export PI_SERVER_PODCAST_MANAGER_SCRIPT="${PI_SERVER_MEDIA_SCRIPT_DIR}/podcast-manager"
export PI_SERVER_MASHPODDER_SCRIPT="${PI_SERVER_MEDIA_SCRIPT_DIR}/mashpodder.sh"

export PI_SERVER_MEDIA_DIR="${PI_SERVER_DATA_DIR}/media-server"
export PI_SERVER_PODCASTS="${PI_SERVER_MEDIA_DIR}/Podcasts - New"
export PI_SERVER_PODCASTS_LISTENED="${PI_SERVER_MEDIA_DIR}/Podcasts - Listened"

export PI_SERVER_MEDIA_CONFIG_DIR="${PI_SERVER_DATA_CONFIG_DIR}/media-server"

export PI_SERVER_MINIDLNA_CONFIG_DIR="${PI_SERVER_MEDIA_CONFIG_DIR}/minidlna"
export PI_SERVER_MINIDLNA_DB="${PI_SERVER_MINIDLNA_CONFIG_DIR}/db"

export PI_SERVER_MASHPODDER_CONFIG_DIR="${PI_SERVER_DATA_MAIN_DIR}/podcasts-config-$(hostname)"
export PI_SERVER_MASHPODDER_RSS_FILE="${PI_SERVER_MASHPODDER_CONFIG_DIR}/configuration.txt"
export PI_SERVER_MASHPODDER_ROOT="${PI_SERVER_MEDIA_CONFIG_DIR}/mashpodder"
export PI_SERVER_MASHPODDER_TMP_DIR="${PI_SERVER_MASHPODDER_ROOT}/tmp"
export PI_SERVER_MASHPODDER_DOWNLOAD_LOG="${PI_SERVER_MASHPODDER_ROOT}/daily-download.log"
