#!/bin/bash
# Daily refresh of the media server

# Download new podcasts
su -s /bin/bash -c '@@@@@1@@@@@' www-data

# Force minidlna to reload, so deleted files go away cleanly.
/usr/sbin/service minidlna force-reload &>/dev/null
