#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


# Make sure the certs are in place, and have the correct permissions
OWNCLOUD_CONFIG='/var/www/owncloud/config/config.php' &&
CERT_NAME='owncloud' &&
check-pi-server-cert "Owncloud" "${CERT_NAME}" &&


# Preparation
sudo service nginx stop &&
sudo service php5-fpm stop &&


# Database configuration
PHP_CONF='/etc/php5/conf.d/mysql.ini' &&
sed-install "${DIR}/php-mysql.ini" "${PHP_CONF}" &&
sudo chmod a=r "${PHP_CONF}" &&

if [ ! -e "${OWNCLOUD_CONFIG}" ]; then
    DATABASE_USER_PW="$(get-new-password 'database password to give the newly-created owncloud user')" &&
    read -s -p 'Enter the database root password (created when installing mysql): ' DATABASE_ROOT_PW && echo &&

    mysql --user=root "--password=${DATABASE_ROOT_PW}" <<EOF
CREATE DATABASE IF NOT EXISTS ${PI_SERVER_OWNCLOUD_DB};
GRANT ALL PRIVILEGES ON ${PI_SERVER_OWNCLOUD_DB}.* TO '${PI_SERVER_OWNCLOUD_DB_USER}'@'localhost' IDENTIFIED BY '${DATABASE_USER_PW}';
EOF

fi

sudo service mysql restart &&


# Storage directory
sudo mkdir -p "${PI_SERVER_OWNCLOUD_DATA_PATH}" &&
sudo chown www-data:www-data "${PI_SERVER_OWNCLOUD_DATA_PATH}" &&
sudo chmod o-rwx "${PI_SERVER_OWNCLOUD_DATA_PATH}" &&


# Install owncloud
APT_DIR='/etc/apt/sources.list.d' &&
APT_DST="${APT_DIR}/owncloud.list" &&
sudo mkdir -p "${APT_DIR}" &&
sudo chmod go-w "${APT_DIR}" &&
sed-install "${DIR}/owncloud.list" "${APT_DST}" &&
sudo chmod a=r "${APT_DST}" &&

wget http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/Release.key -O - | sudo apt-key add - &&

sudo apt-get update &&
# Get manual confirmation in case there is an update, which might break things
sudo apt-get install owncloud &&
sudo chown www-data:www-data /var/www/owncloud/apps &&


# Configure nginx
CONF='/etc/nginx/sites-enabled/owncloud' &&
sed-install "${DIR}/owncloud-nginx-template" "${CONF}" \
            "${PI_SERVER_IP}" \
            "$(pi-server-cert "${CERT_NAME}")" \
            "$(pi-server-key "${CERT_NAME}")" \
            "${PI_SERVER_CRL}"
sudo chmod a=r "${CONF}" &&


# First-time owncloud config
if [ ! -e "${OWNCLOUD_CONFIG}" ]; then
    OWNCLOUD_ADMIN_PW="$(get-new-password 'new password for the owncloud admin user')" &&
    AUTOCONFIG='/var/www/owncloud/config/autoconfig.php' &&
    sed-install "${DIR}/autoconfig-template" "${AUTOCONFIG}" \
                "${PI_SERVER_OWNCLOUD_DB}" \
                "${PI_SERVER_OWNCLOUD_DB_USER}" \
                "${DATABASE_USER_PW}" \
                "${OWNCLOUD_ADMIN_PW}" \
                "${PI_SERVER_OWNCLOUD_DATA_PATH}" &&
    sudo chown www-data:www-data "${AUTOCONFIG}" &&
    sudo chmod go-rwx "${AUTOCONFIG}"
fi


# Cleanup
sudo service php5-fpm start &&
sudo service nginx start &&
echo 'About to display instructions' &&
enter-to-continue &&


less <<EOF
To configure owncloud, go to https://${PI_SERVER_IP} and login as admin, with the password you chose.

Once you can login and see the files on the server, go to the menu, select 'admin', and set the following settings:

[Federated Cloud Sharing]
Tick both boxes

[Cron]
Tick 'cron'

[Sharing]
Untick 'Allow apps to use the Share API', and all the other boxes should disappear

[Security]
Tick 'Enforce HTTPS' and 'Enforce HTTPS for subdomains'

[Email Server]
Mode: php
From address: owncloud@${PI_SERVER_FQDN}


Go to the menu, select 'personal', and fill in the email address field with the address notifications should be sent to.


Set up users as desired; in each one, make sure the quota is unlimited, and delete the pre-existing default files.


For the user, create three folders in the root:
    main         - data here will be synced with this server's clients, and backed up on the other server
    local-only   - data here will only be synced with this server's clients
    remote       - folder containing mount points to other server's 'main'


As admin, go to apps, enable the 'external storage' app, then go back to admin and configure it:
Untick 'Enable user external storage'

Add the share as an ownCloud server - folder name should be 'remote/<something>', remote folder should be 'main'.
EOF
