#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


sudo apt-get update &&

sudo apt-get -y install dialog &&


if [ ! -e "${PI_SERVER_DIR}" ]; then
    # Aggressively remove all the preinstalled stuff - but only the
    # first time! Some of this will probably come back later.
    sudo apt-get -y remove --purge --auto-remove alsa-base alsa-utils apt-listchanges build-essential cifs-utils cpp debconf-utils debian-reference-en desktop-file-utils dpkg-dev ecryptfs-utils fbset fontconfig fonts-freefont-ttf gconf2-common gdb gnome-themes-standard-data gsfonts-x11 info install-info java-common libasound2 libwibble-dev libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxdmcp6 libxfont1 libxpm4 linux-libc-dev lsof lua5.1 lxde-icon-theme make menu-xdg ncdu nfs-common parted pkg-config plymouth python-serial python3-numpy python3-serial samba-common smbclient v4l-utils whiptail x11-common xdg-utils xfonts-utils &&

    if real-pi; then
        sudo apt-get -y remove --purge --auto-remove libraspberrypi-bin libraspberrypi-dev libraspberrypi-doc libraspberrypi0 luajit omxplayer penguinspuzzle python-pifacecommon python-pifacedigitalio python-rpi.gpio python3-pifacecommon python3-pifacedigital-scratch-handler python3-pifacedigitalio python3-rpi.gpio raspberrypi-artwork || exit 1
    fi

    sudo tasksel remove desktop &&
    sudo rm -f '/etc/apt/sources.list.d/wolfram.list' || exit 1
fi


sudo apt-get -y install avahi-daemon console-setup curl etckeeper hdparm nginx-naxsi ntfs-3g openssh-server openvpn ssmtp supervisor tmux unattended-upgrades wget wpasupplicant &&

sudo apt-get update &&
sudo apt-get -y upgrade &&
# No auto-confirm on dist-upgrade, for safety reasons
sudo apt-get dist-upgrade &&

echo &&
echo "Use 'aptitude' to check for any other packages that should be removed; once loaded, type 'l', then '~i!~M' to see all installed non-automatic packages." &&
echo "Reboot at this point to make sure nothing is broken, and also check ps -elf to see what's running" &&
enter-to-continue
