#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


if [ "$(id -un)" = 'pi' ]; then
    echo "Run this as the new user - can't delete 'pi' while still logged in as it!"
    exit 1
fi

if id -u 'pi' &>/dev/null; then
    sudo deluser --remove-all-files 'pi' || exit 1
fi

sudo rm -rf /home/pi &&

function lockout() {
    if id -u "${1}" &>/dev/null; then
        sudo passwd -l "${1}" &&
        sudo chsh -s /usr/sbin/nologin "${1}"
    fi
}

sudo passwd -l root &&
lockout daemon &&
lockout bin &&
lockout sys &&
lockout sync &&
lockout games &&
lockout man &&
lockout lp &&
lockout mail &&
lockout news &&
lockout uucp &&
lockout proxy &&
lockout www-data &&
lockout backup &&
lockout list &&
lockout irc &&
lockout gnats &&
lockout nobody &&
lockout systemd-timesync &&
lockout systemd-network &&
lockout systemd-resolve &&
lockout systemd-bus-proxy &&
lockout Debian-exim &&
lockout messagebus &&
lockout avahi &&
lockout ntp &&
lockout sshd &&
lockout statd &&

echo &&
echo "Now remove all references to user 'pi' from /etc/sudoers, if they exist, and comment out the similar line in /etc/sudoers.d/010_pi-nopasswd, if it exists." &&
enter-to-continue
