#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


if [ "$(id -un)" = 'pi' ]; then
    echo "Run this as the new user - can't delete 'pi' while still logged in as it!"
    exit 1
fi

function remove-if-exists()
{
    if id -u "${1}" &>/dev/null; then
        sudo deluser --remove-all-files "${1}"
    fi
}

remove-if-exists pi &&
remove-if-exists games &&
remove-if-exists mail &&
remove-if-exists news &&
remove-if-exists uucp &&
remove-if-exists irc &&
remove-if-exists gnats &&
remove-if-exists statd &&
remove-if-exists usbmux &&
remove-if-exists list &&

sudo rm -rf /home/pi &&

function lockout()
{
    if id -u "${1}" &>/dev/null; then
        sudo passwd -l "${1}" &&
        sudo chsh -s /usr/sbin/nologin "${1}"
    fi
}

sudo passwd -l root &&
lockout daemon &&
lockout bin &&
lockout sys &&
lockout sync &&
lockout man &&
lockout proxy &&
lockout www-data &&
lockout backup &&
lockout nobody &&
lockout libuuid &&
lockout sshd &&
lockout ntp &&
lockout lp &&
lockout messagebus &&
lockout mysql &&
lockout avahi &&

echo &&
echo "Now remove all references to user 'pi' from /etc/sudoers" &&
enter-to-continue
