#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


INTERFACES='/etc/network/interfaces'
DHCPCD_CONF='/etc/dhcpcd.conf'

if [ -z "${PI_SERVER_WAN_IFACE}" ]; then
    sed-install "${DIR}/interfaces-normal" "${INTERFACES}" &&
    sed-install "${DIR}/dhcpcd-conf-template" "${DHCPCD_CONF}" \
                "${PI_SERVER_LAN_IFACE}" || exit 1
else
    sed-install "${DIR}/interfaces-router" "${INTERFACES}" \
                "${PI_SERVER_WAN_IFACE}" \
                "${PI_SERVER_LAN_IFACE}" \
                "${PI_SERVER_IP}" &&
    sed-install "${DIR}/dhcpcd-conf-template" "${DHCPCD_CONF}" \
                "${PI_SERVER_WAN_IFACE}" || exit 1
fi

sudo chmod a=r "${INTERFACES}" &&
sudo chmod a=r "${DHCPCD_CONF}"
