#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


INTERFACES='/etc/network/interfaces'

if [ -z "${PI_SERVER_WAN_IFACE}" ]; then
    sed-install "${DIR}/interfaces-normal" "${INTERFACES}"
else
    sed-install "${DIR}/interfaces-router" "${INTERFACES}" \
                "${PI_SERVER_WAN_IFACE}" \
                "${PI_SERVER_LAN_IFACE}" \
                "${PI_SERVER_IP}"
fi

sudo chmod a=r "${INTERFACES}"
