#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


# IPtables
sudo mkdir -p "${PI_SERVER_IPTABLES_DIR}" &&


sed-install "${DIR}/iptables-rules" "${PI_SERVER_IPTABLES_RULES}" &&
sudo chmod a=r "${PI_SERVER_IPTABLES_RULES}" &&


sed-install "${DIR}/firewall-common.bash" "${PI_SERVER_IPTABLES_COMMON_BASH}" \
            "${PI_SERVER_IPTABLES_TCP_OPEN_BOOT}" \
            "${PI_SERVER_IPTABLES_UDP_OPEN_BOOT}" &&
sudo chmod a=r "${PI_SERVER_IPTABLES_COMMON_BASH}" &&


SCRIPT='/etc/network/if-pre-up.d/iptables' &&
sed-install "${DIR}/iptables" "${SCRIPT}" \
            "${PI_SERVER_IPTABLES_COMMON_BASH}" \
            "${PI_SERVER_IPTABLES_RULES}" &&
sudo chmod u=rx "${SCRIPT}" &&
sudo chmod go-rwx "${SCRIPT}" &&


sed-install "${DIR}/port" "${PI_SERVER_IPTABLES_PORT_SCRIPT}" \
            "${PI_SERVER_IPTABLES_COMMON_BASH}" &&
sudo chmod a=rx "${PI_SERVER_IPTABLES_PORT_SCRIPT}" &&


# Enable routing
SYSCTL_CONF='/etc/sysctl.conf'

if ! grep '^net.ipv4.ip_forward' "${SYSCTL_CONF}" &>/dev/null; then
    echo 'net.ipv4.ip_forward=1' | sudo tee -a "${SYSCTL_CONF}" >/dev/null
elif grep '^net.ipv4.ip_forward=0$' "${SYSCTL_CONF}" >&/dev/null; then
    sudo sed -i 's/^net.ipv4.ip_forward=0$/net.ipv4.ip_forward=1/g' "${SYSCTL_CONF}"
elif ! grep '^net.ipv4.ip_forward=1$' "${SYSCTL_CONF}" &>/dev/null; then
    echo
    echo "Something's up with ${SYSCTL_CONF}; better fix it manually"
fi


echo "Reboot to enable the firewall." &&
enter-to-continue
