#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


LISTCHANGES_CONF='/etc/apt/listchanges.conf'

sed-install "${DIR}/listchanges.conf" "${LISTCHANGES_CONF}" &&
sudo chmod a=r "${LISTCHANGES_CONF}"
