#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


# Setup generic nginx config (not a specific site)
CONF_TARGET='/etc/nginx/nginx.conf' &&
sed-install "${DIR}/nginx.conf" "${CONF_TARGET}" &&
sudo chmod a=r "${CONF_TARGET}" &&


# Delete the pre-installed default site
sudo rm -f '/etc/nginx/sites-enabled/default' &&


# Configure generic php settings
PHP_INI='/etc/php5/fpm/php.ini' &&

if ! grep '^cgi.fix_pathinfo' "${PHP_INI}" &>/dev/null; then
    echo 'cgi.fix_pathinfo=0' | sudo tee -a "${PHP_INI}" >/dev/null
elif grep '^cgi.fix_pathinfo=1$' "${PHP_INI}" >&/dev/null; then
    sudo sed -i 's/^cgi.fix_pathinfo=1$/cgi.fix_pathinfo=0/g' "${PHP_INI}"
elif ! grep '^cgi.fix_pathinfo=0$' "${PHP_INI}" &>/dev/null; then
    echo
    echo "Something's up with ${PHP_INI}; better fix it manually"
fi

if ! grep '^default_charset' "${PHP_INI}" &>/dev/null; then
    echo 'default_charset = "UTF-8"' | sudo tee -a "${PHP_INI}" >/dev/null
else
    if ! grep '^default_charset = "UTF-8"' "${PHP_INI}" &>/dev/null; then
        echo
        echo "Something's up with ${PHP_INI}; better fix it manually"
    fi
fi


# Firewall
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open-at-boot 443 tcp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open 443 tcp &&


stop-web-services &&
start-web-services
