#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


# Setup user
NEW_USER='shutdownd'

if ! grep "${NEW_USER}" '/etc/passwd' &>/dev/null; then
    sudo adduser --disabled-login --no-create-home --shell /usr/sbin/nologin --gecos "${NEW_USER}" "${NEW_USER}" || exit 1
fi

sudo passwd -l "${NEW_USER}" &&
sudo chsh -s /usr/sbin/nologin "${NEW_USER}" &&


# Setup actual script
sed-install "${DIR}/shutdownd" "${PI_SERVER_SHUTDOWND_SCRIPT}" &&
sudo chmod a=rx "${PI_SERVER_SHUTDOWND_SCRIPT}" &&


# Setup permissions so the new user can call shutdown - and only shutdown - through sudo
SUDOERS_DST='/etc/sudoers.d/shutdownd' &&
sed-install "${DIR}/sudoers-shutdownd-template" "${SUDOERS_DST}" "$(hostname)"
sudo chmod ug=r "${SUDOERS_DST}" &&
sudo chmod o-rwx "${SUDOERS_DST}" &&


# Set it up to run at boot
SUPERVISOR_DST='/etc/supervisor/conf.d/shutdownd.conf' &&
sed-install "${DIR}/supervisor-shutdownd" "${SUPERVISOR_DST}" "${PI_SERVER_SHUTDOWND_SCRIPT}" &&
sudo chmod a=r "${SUPERVISOR_DST}" &&


# Firewall
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open-at-boot 23145 tcp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open 23145 tcp
