#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&

sudo mkdir -p "${PI_SERVER_BACKUP_SCRIPT_DIR}" "${PI_SERVER_BACKUP_PAUSE_DIR}" &&

RSNAPSHOT_CONF='/etc/rsnapshot.conf'
sed-install "${DIR}/rsnapshot.conf" "${RSNAPSHOT_CONF}" \
            "${PI_SERVER_BACKUP_MAIN_DIR}" \
            "${PI_SERVER_DATA_MAIN_DIR}" \
            "$(hostname)" &&
sudo chmod a=r "${RSNAPSHOT_CONF}" &&

sed-install "${DIR}/pi-server-backup" "${PI_SERVER_BACKUP_SCRIPT}" \
            "${PI_SERVER_NOTIFICATION_EMAIL_SCRIPT}" \
            "${PI_SERVER_BACKUP_LOCK}" \
            "${PI_SERVER_BACKUP_LAST_RUN}" \
            "${PI_SERVER_DATA_MAIN_DIR}" \
            "${PI_SERVER_BACKUP_MOUNT_DIR}" \
            "${PI_SERVER_BACKUP_PAUSE_DIR}" \
            "${PI_SERVER_BACKUP_LOG_FILE}" &&
sudo chmod a=rx "${PI_SERVER_BACKUP_SCRIPT}"
