#!/bin/bash
# Generate the main pi-server web page. Should run as root.

INDEX='@@@@@1@@@@@/index.html'

test -f "${INDEX}" && chmod u+w "${INDEX}"
cat '@@@@@3@@@@@' '@@@@@2@@@@@'/* '@@@@@4@@@@@' > "${INDEX}"
chmod a=r "${INDEX}"
