#!/bin/bash
# This file runs at boot to initialise the firewall

source '@@@@@1@@@@@' || exit 1

/sbin/iptables-restore < '@@@@@2@@@@@'

WAN_IFACE="$(cat '@@@@@3@@@@@')"
if [ -z "${WAN_IFACE}" ]; then
    IFACE_PART=''
else
    IFACE_PART="! -i ${WAN_IFACE}"
fi

function do-protocol() {
    local PROTOCOL="${1}"
    local FILE="$(open-at-boot-file "${PROTOCOL}")"

    if [ -f "${FILE}" ]; then
        while read port; do
            if valid-port "${port}"; then
                /sbin/iptables -I INPUT -p "${PROTOCOL}" --dport "${port}" "${IFACE_PART}" -j ACCEPT
            fi
        done < "${FILE}"
    fi
}

do-protocol 'tcp'
do-protocol 'udp'

exit 0
