#!/bin/bash
# This file runs at boot to initialise the firewall

source '@@@@@1@@@@@' || exit 1

/sbin/iptables-restore < '@@@@@2@@@@@'

function do-protocol()
{
    local PROTOCOL="${1}"
    local FILE="$(open-at-boot-file "${PROTOCOL}")"

    if [ -f "${FILE}" ]; then
        while read port; do
            if valid-port "${port}"; then
                /sbin/iptables -I INPUT -p "${PROTOCOL}" --dport "${port}" -j ACCEPT
            fi
        done < "${FILE}"
    fi
}

do-protocol 'tcp'
do-protocol 'udp'

exit 0
