#!/bin/bash
# Run an OpenVPN connection for several hours overnight, to avoid overloading slow connections during the day

CONFIG_FILE='@@@@@1@@@@@'
LOG_FILE='@@@@@2@@@@@'
EMAIL_SCRIPT='@@@@@3@@@@@'
TIMEOUT_DURATION='7h'

test ! -f "${CONFIG_FILE}" && exit 0

CONFIG="$(grep -v '^#' "${CONFIG_FILE}" | head -n 1)"

test -z "${CONFIG}" && exit 0

CONFIG_PATH="/etc/openvpn/${CONFIG}"

function fail() {
    "${EMAIL_SCRIPT}" 'OpenVPN nightly failed' "${@}"
    echo "${@}" >> "${LOG_FILE}"
    exit 1
}


:> "${LOG_FILE}"

test ! -f "${CONFIG_PATH}" && fail 'Specified config file does not exist.'

timeout "${TIMEOUT_DURATION}" openvpn --cd /etc/openvpn --config "${CONFIG_PATH}" &>>"${LOG_FILE}" &

exit 0
