#!/bin/bash
# Run all the pi-server cron scripts

if [ -e '@@@@@3@@@@@' ]; then
    # Cron script disabled
    exit 0
fi

# Run main backup script
if [ -x '@@@@@2@@@@@' ]; then
    '@@@@@2@@@@@'
fi

# Run all other cron scripts
find '@@@@@1@@@@@' -type f -executable | LC_ALL=C sort | while read line; do
    "${line}"
done
