#!/bin/bash
# Run all the pi-server cron scripts

# Run main backup script
if [ -x '@@@@@2@@@@@' ]; then
    '@@@@@2@@@@@'
fi

# Run all other cron scripts
find '@@@@@1@@@@@' -type f -executable | LC_ALL=C sort | while read line; do
    "${line}"
done
