#!/bin/bash
# Manipulate the ports that open at boot

source '@@@@@1@@@@@' || exit 1

function opens()
{
    if [ -f "${BOOTFILE}" ]; then
        if grep -x "${PORT}" "${BOOTFILE}" &>/dev/null; then
            echo 'Yes'
            return 0
        fi
    fi

    echo 'No'
    return 1
}

function open()
{
    if ! opens &>/dev/null; then
        echo "${PORT}" | sudo tee -a "${BOOTFILE}" &>/dev/null
    fi
}

function dont-open()
{
    if [ -f "${BOOTFILE}" ]; then
        sudo sed -i "/^${PORT}\$/d" "${BOOTFILE}"
    fi
}

COMMANDS='opens|open|dont-open'
process-args "${@}"
