#!/bin/bash
# Send a notification email to the default target address

FROM_FILE='@@@@@1@@@@@'
TO_FILE='@@@@@2@@@@@'

function usage()
{
    echo "Usage: $(basename "${0}") subject body"
    exit 1
}

test -z "${1}" && usage
test -z "${2}" && usage

FROM="$(cat "${FROM_FILE}")"
TO="$(cat "${TO_FILE}")"

function no-values()
{
    echo 'Default values are invalid'
    exit 1
}

test -z "${FROM}" && no-values
test -z "${TO}" && no-values

ssmtp "${TO}" <<EOF
From: Notification <notification@${FROM}>
To: ${TO}
Subject: [Notification from: $(hostname)] ${1}

${2}

EOF
