#!/bin/bash

sysctl -w net.ipv4.ip_forward=1

function iface-exists()
{
    /sbin/ifconfig -s | grep "${1}"
}

if [ ! -e /tmp/fakeRouter.done ] &&
   iface-exists lo &&
   iface-exists eth0 &&
   iface-exists eth1; then

    ip route add default via @@@@@1@@@@@ dev eth0

    iptables -A INPUT -i lo -j ACCEPT
    ipatbles -A INPUT -i eth1 -j ACCEPT
    iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    iptables -A INPUT -j DROP
    iptables -A FORWARD -i eth1 -j ACCEPT
    iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    iptables -A FORWARD -j DROP
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

    # Port forward for VPN connection
    iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 1194 -j DNAT --to @@@@@2@@@@@:1194
    iptables -I FORWARD -p tcp -d @@@@@2@@@@@ --dport 1194 -j ACCEPT

    touch /tmp/fakeRouter.done
fi
