#!/bin/bash

ip route add default via @@@@@1@@@@@ dev eth0
sysctl -w net.ipv4.ip_forward=1

if [ ! -e /tmp/fakeRouter.done ]; then
    iptables -A INPUT -i lo -j ACCEPT
    ipatbles -A INPUT -i eth1 -j ACCEPT
    iptables -A FORWARD -i eth1 -j ACCEPT
    iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    iptables -A INPUT -j DROP
    iptables -A FORWARD -j DROP
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

    touch /tmp/fakeRouter.done
fi
