#!/bin/bash

sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o @@@@@1@@@@@ -j MASQUERADE

# Apparently, packets for the pi's subnets were being routed through
# the NAT interface and then through the host-only interface... make
# sure they really are inaccessible (host 192.168.56.56 must not exist)
ip route add 192.168.57.0/24 via 192.168.56.56 dev @@@@@2@@@@@
ip route add 192.168.58.0/24 via 192.168.56.56 dev @@@@@2@@@@@

exit 0
