# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_EXPERIMENTAL"] = "disks"

require 'json'

required_plugins = %w( vagrant-reload )
required_plugins.each do |plugin|
  exec "vagrant plugin install #{plugin} && vagrant #{ARGV.join(" ")}" unless
    Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

# Config defines the IP addresses of the VMs, so it can be shared with ansible
$c = JSON.parse(File.read('config.json'))
$addrs = $c["addrs"]
$masks = $c["masks"]

def sync_folders(vm)
  vm.vm.synced_folder "..", "/vagrant", type: "rsync", rsync__exclude: [".git/", ".ansible-galaxy/"]
end

def internet(config)
  config.vm.define "internet" do |internet|
    internet.vm.box = "debian/stretch64"
    internet.vm.hostname = "internet"
    internet.vm.network "private_network", ip: $addrs["internet"]
    sync_folders(internet)
    internet.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "setup/internet.yml"
      ansible.extra_vars = {
        nonexistent_wan_ip: $addrs["nonexistent_wan"],
        lan1_mask: $masks["lan1"],
        lan2_mask: $masks["lan2"]
      }
    end
    internet.vm.provision :reload
  end
end


def router(config, name, wan_ip, lan_ip, pi_ip, pi_vpn_mask)
  config.vm.define name do |box|
    box.vm.box = "debian/stretch64"
    box.vm.hostname = name
    box.vm.network "private_network", ip: wan_ip
    box.vm.network "private_network", ip: lan_ip
    sync_folders(box)
    box.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "setup/router.yml"
      ansible.extra_vars = {
        internet_ip: $addrs["internet"],
        pi_ip: pi_ip,
        pi_vpn_mask: pi_vpn_mask
      }
    end
    box.vm.provision :reload
  end
end


def pi(config, name, pi_ip, router_lan_ip, pi_lan_mask, pi_vpn_mask)
  config.vm.define name do |box|
    box.vm.box = "debian/stretch64"
    box.vm.hostname = name
    box.vm.network "private_network", ip: pi_ip
    box.vm.disk :disk, size: "100MB", name: "external"
    sync_folders(box)
    box.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "setup/pi.yml"
      ansible.extra_vars = {
        pi_ip: pi_ip,
        router_ip: router_lan_ip,
        internet_ip: $addrs["internet"],
        pi_lan_mask: pi_lan_mask,
        pi_vpn_mask: pi_vpn_mask
      }
    end
    box.vm.provision :reload
  end
end


def ubuntu(config)
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-16.04"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", ip: $addrs["ubuntu"]
    sync_folders(ubuntu)
    ubuntu.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "setup/ubuntu.yml"
      ansible.extra_vars = {
        pi_ip: $addrs["ubuntu"],
        router_ip: $addrs["internet"],
        internet_ip: $addrs["internet"]
      }
    end
    ubuntu.vm.provision :reload
  end
end


Vagrant.configure("2") do |config|
  internet config

  router config, "router1", $addrs["router1_wan"], $addrs["router1_lan"], $addrs["pi1"], $masks["pi1_vpn"]
  router config, "router2", $addrs["router2_wan"], $addrs["router2_lan"], $addrs["pi2"], $masks["pi2_vpn"]

  pi config, "pi1", $addrs["pi1"], $addrs["router1_lan"], $masks["lan1"], $masks["pi1_vpn"]
  pi config, "pi2", $addrs["pi2"], $addrs["router2_lan"], $masks["lan2"], $masks["pi2_vpn"]

  ubuntu config
end
