#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DIR}/../01-core/common.bash"

function usage()
{
    echo "Usage: $(basename "${0}") new_ca_dir your_name"
    echo "    new_ca_dir must not already exist, and should probably be somewhere encrypted!"
    echo "    your_name will be used as the 'organisation' field in the created certificates"
    exit 1
}

test -z "${1}" && usage
test -e "${1}" && usage
test -z "${2}" && usage

CA_DIR="${1}"
YOUR_NAME="${2}"

PASSWD="$(get-new-password 'new password for the root CA key')"


# Create the directory structure
mkdir -p "${CA_DIR}" &&
mkdir -p "${CA_DIR}/ca" &&
mkdir -p "${CA_DIR}/data" &&
mkdir -p "${CA_DIR}/certs/server" &&
mkdir -p "${CA_DIR}/certs/client" &&
cp -a "${DIR}/scripts" "${CA_DIR}/scripts" &&

cp "${DIR}/openssl-conf-template" "${CA_DIR}/openssl.conf" &&
sed -i "s|@@@@@1@@@@@|${YOUR_NAME}|g" "${CA_DIR}/openssl.conf" &&

cp "${DIR}/script-templates/make-client-cert" "${CA_DIR}/scripts/make-client-cert" &&
sed -i "s|@@@@@1@@@@@|${YOUR_NAME}|g" "${CA_DIR}/scripts/make-client-cert" &&

cp "${DIR}/script-templates/make-pi-server-certs" "${CA_DIR}/scripts/make-pi-server-certs" &&
sed -i "s|@@@@@1@@@@@|${YOUR_NAME}|g" "${CA_DIR}/scripts/make-pi-server-certs" &&

touch "${CA_DIR}/data/index.txt" &&
echo 00 > "${CA_DIR}/data/serial.txt" &&
chmod -R go-rwx "${CA_DIR}" &&

export CA_DIR &&


# Create the root CA certificate; valid for 10 years
exec 3<<EOF
${PASSWD}
EOF

openssl req -config "${CA_DIR}/openssl.conf" -x509 -days 3650 -newkey rsa -keyout "${CA_DIR}/ca/ca.key" -out "${CA_DIR}/ca/ca.crt" -outform PEM -passout fd:3 &&

chmod u=r "${CA_DIR}/ca/ca.crt" "${CA_DIR}/ca/ca.key" &&
chmod go-rwx "${CA_DIR}/ca/ca.key" &&
chmod go=r "${CA_DIR}/ca/ca.crt" &&


# Create the CRL
exec 3<<EOF
${PASSWD}
EOF

openssl ca -config "${CA_DIR}/openssl.conf" -gencrl -out "${CA_DIR}/ca/crl" -passin fd:3 &&

chmod u=rw "${CA_DIR}/ca/crl" &&
chmod go=r "${CA_DIR}/ca/crl" &&


# Create the OpenVPN pre-shared key (extra layer on top of TLS)
openvpn --genkey --secret "${CA_DIR}/ca/openvpn-tls-auth.key" &&
chmod u=r "${CA_DIR}/ca/openvpn-tls-auth.key" &&
chmod go-rwx "${CA_DIR}/ca/openvpn-tls-auth.key"
