#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function usage()
{
    echo "Usage: $(basename "${0}") new_ca_dir"
    echo "    new_ca_dir must not already exist, and should probably be somewhere encrypted!"
    exit 1
}

test -z "${1}" && usage
test -e "${1}" && usage

CA_DIR="${1}"

read -s -p "Enter the new password for the root CA key: " PASSWD && echo &&
read -s -p "Enter the password again to confirm: " PASSWD2 && echo &&

if [ "${PASSWD}" != "${PASSWD2}" ]; then
    echo "Error: the passwords do not match"
    exit 1
else
    echo
fi


# Create the directory structure
mkdir -p "${CA_DIR}" &&
mkdir -p "${CA_DIR}/ca" &&
mkdir -p "${CA_DIR}/data" &&
mkdir -p "${CA_DIR}/certs/server" &&
mkdir -p "${CA_DIR}/certs/client" &&
cp -a "${DIR}/scripts" "${CA_DIR}/scripts" &&
cp "${DIR}/openssl.conf" "${CA_DIR}/openssl.conf" &&
touch "${CA_DIR}/data/index.txt" &&
echo 00 > "${CA_DIR}/data/serial.txt" &&
chmod -R go-rwx "${CA_DIR}" &&

export CA_DIR &&


# Create the root CA certificate; valid for 10 years
exec 3<<EOF
${PASSWD}
EOF

openssl req -config "${CA_DIR}/openssl.conf" -x509 -days 3650 -newkey rsa -keyout "${CA_DIR}/ca/ca.key" -out "${CA_DIR}/ca/ca.crt" -outform PEM -passout fd:3 &&

chmod u=r "${CA_DIR}/ca/ca.crt" "${CA_DIR}/ca/ca.key" &&
chmod go-rwx "${CA_DIR}/ca/ca.key" &&
chmod go=r "${CA_DIR}/ca/ca.crt" &&


# Create the CRL
exec 3<<EOF
${PASSWD}
EOF

openssl ca -config "${CA_DIR}/openssl.conf" -gencrl -out "${CA_DIR}/ca/crl" -passin fd:3 &&

chmod u=rw "${CA_DIR}/ca/crl" &&
chmod go=r "${CA_DIR}/ca/crl"


# Create the OpenVPN pre-shared key (extra layer on top of TLS)
openvpn --genkey --secret "${CA_DIR}/ca/openvpn-tls-auth.key"
chmod u=r "${CA_DIR}/ca/openvpn-tls-auth.key"
chmod go-rwx "${CA_DIR}/ca/openvpn-tls-auth.key"
