from typing import Any, ContextManager, List, Optional
from conftest import CronRunner, ShadowDir, ShadowFile
from testinfra.backend.base import CommandResult
from testinfra.modules.addr import Addr
from testinfra.modules.file import File
from testinfra.modules.package import Package
from testinfra.modules.user import User
from testinfra.modules.service import Service
from testinfra.modules.sudo import Sudo

class Host:
    def addr(self, addr: str) -> Addr: ...
    def run(self, command: str, *args: Any) -> CommandResult: ...
    def run_expect(self, expected: List[int], command: str, *args: Any) -> None: ...
    def check_output(self, command: str, *args: Any) -> str: ...
    def file(self, path: str) -> File: ...
    def shadow_file(self, path: str) -> ShadowFile: ...
    def shadow_dir(self, path: str) -> ShadowDir: ...
    def package(self, package: str) -> Package: ...
    def user(self, user: str) -> User: ...
    def sudo(self, user: Optional[str] = None) -> Sudo: ...
    def service(self, name: str) -> Service: ...
    def run_crons(self, time: str = '', cmd_to_watch: str = '') -> CronRunner: ...
    def client_ip(self) -> str: ...
    def disable_login_emails(self) -> ContextManager[None]: ...
