from typing import Any, Optional
from testinfra.modules.addr import Addr
from testinfra.modules.file import File
from testinfra.modules.package import Package
from testinfra.modules.user import User
from testinfra.modules.sudo import Sudo

class Host:
    def addr(self, addr: str) -> Addr: ...
    def check_output(self, command: str, *args: Any) -> str: ...
    def file(self, path: str) -> File: ...
    def package(self, package: str) -> Package: ...
    def user(self, user: str) -> User: ...
    def sudo(self, user: Optional[str] = None) -> Sudo: ...
