from typing import Any
from testinfra.modules.addr import Addr
from testinfra.modules.package import Package

class Host:
    def addr(self, addr: str) -> Addr: ...
    def check_output(self, command: str, *args: Any) -> str: ...
    def package(self, package: str) -> Package: ...
