#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" &&
source "${DIR}/common.bash" &&


sudo apt-get update &&
sudo apt-get -y install minidlna &&


MINIDLNA_DEFAULT='/etc/default/minidlna' &&
sudo sed -i 's/^#USER="minidlna"$/USER="www-data"/g' "${MINIDLNA_DEFAULT}" &&
sudo sed -i 's/^#GROUP="minidlna"$/GROUP="www-data"/g' "${MINIDLNA_DEFAULT}" &&
# Workaround 'force-reload' in the init script no longer working; now always force reload.
sudo sed -i 's/^DAEMON_OPTS=""$/DAEMON_OPTS="-R"/g' "${MINIDLNA_DEFAULT}" &&


MINIDLNA_CONF='/etc/minidlna.conf' &&
sed-install "${DIR}/minidlna-conf-template" "${MINIDLNA_CONF}" \
            "${PI_SERVER_MEDIA_DIR}" \
            "${PI_SERVER_MINIDLNA_DB}" \
            "${PI_SERVER_LAN_IFACE}" &&
sudo chmod a=r "${MINIDLNA_CONF}" || exit 1


function minidlna-dir() {
    while (($#)); do
        sudo mkdir -p "${1}" &&
        sudo chown www-data:www-data "${1}" &&
        sudo chmod go-rwx "${1}" || return 1
        shift
    done
}

minidlna-dir "${PI_SERVER_MEDIA_DIR}" \
             "${PI_SERVER_MEDIA_CONFIG_DIR}" \
             "${PI_SERVER_MINIDLNA_CONFIG_DIR}" \
             "${PI_SERVER_MINIDLNA_DB}" &&


# Setup webpage
DST="${PI_SERVER_WEB_PAGE_PARTS_DIR}/01-minidlna" &&
sed-install "${DIR}/webpage-template" "${DST}" &&
sudo chmod a=r "${DST}" &&

sudo "${PI_SERVER_WEB_PAGE_GENERATE}" || exit 1


# Firewall
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open-at-boot 8200 tcp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open-at-boot 1900 udp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open 8200 tcp &&
"${PI_SERVER_IPTABLES_PORT_SCRIPT}" open 1900 udp &&


CRONJOB="${PI_SERVER_CRON_NORMAL_DIR}/media-server" &&
sed-install "${DIR}/media-server-cron" "${CRONJOB}" &&
sudo chmod a=rx "${CRONJOB}" &&

sudo touch "${PI_SERVER_CRON_PAUSE_DIR}/minidlna.service" &&


sudo service minidlna force-reload &&


cat <<EOF &&

To add media to the server, place or symlink it (using the absolute path) in '${PI_SERVER_MEDIA_DIR}'.

EOF
enter-to-continue
