#!/usr/bin/env python3

import os.path
import re
import eyed3
import ftfy

LOG_FILE = "@@@@@1@@@@@"
PODCASTS_DIR = "@@@@@2@@@@@"

eyed3.log.setLevel("ERROR")


def pretty_print(podcast_dir, filename):
    try:
        mp3 = eyed3.load(os.path.join(PODCASTS_DIR, podcast_dir, filename))
        if mp3 and mp3.tag and mp3.tag.title:
            s = '"%s"' % ftfy.fix_text(mp3.tag.title)
            if mp3.tag.artist:
                s += ", by %s" % ftfy.fix_text(mp3.tag.artist)
            s += " (%s)" % filename
            return s
        else:
            return filename
    except Exception:
        return filename


total_matcher = re.compile(r"^Total downloads: ([0-9]+)$")
file_matcher = re.compile(r"^(.+) downloaded to (.+)$")

total = 0
files = []

with open(LOG_FILE, encoding="utf-8") as f:
    for line in f:
        line = line.strip()

        match = total_matcher.match(line)
        if match:
            total = int(match.group(1))

        match = file_matcher.match(line)
        if match:
            files.append((match.group(2), match.group(1)))

files.sort()

print("Downloaded %d new podcast%s" % (total, "" if total == 1 else "s"))

folder = ""

for foldername, filename in files:
    if foldername != folder:
        print()
        print("%s:" % foldername)
    folder = foldername

    print("  %s" % pretty_print(folder, filename))

print()
